server:
  port: 8081

spring:
  application:
    name: comment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.50.181.73:3308/tms?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: remote
    password: dlut

  redis:
    host: 47.109.17.8
    port: 6378
    timeout: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



mybatis-plus:
  global-config:
    db-config:

      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)




